[build]
command = """
pip install --upgrade pip
pip install pandas numpy openpyxl
pip install -r requirements.txt
"""

[deploy]
startCommand = "python bot.py"

[env]
PORT = "8080"
PYTHON_VERSION = "3.9.16"
